name: podNET opinionated .NET build, test and NuGet publish GitHub Action
inputs:
  skip-auto-checkout: { }
  skip-auto-setup-dotnet: { }
  skip-prepack-debug: { }
  skip-test: { }
  skip-pack: { }
  version: { default: "$(echo ${{ github.ref_name }} | sed 's/^v//')" }
  commit: { default: "${{ github.sha }}" }
  nuget-push-api-key: { }
  skip-store-artifact: { }
  skip-store-release: { }
runs:
  using: composite
  steps:      
    - if: ${{ !inputs.skip-auto-checkout }}
      uses: actions/checkout@v4
    - if: ${{ !inputs.skip-auto-setup-dotnet }}
      uses: actions/setup-dotnet@v4
    - if: ${{ !inputs.skip-prepack-debug }}
      run: dotnet pack -c debug
      shell: pwsh
    - if: ${{ !inputs.skip-test }}
      run: dotnet test
      shell: pwsh
    - if: ${{ !inputs.skip-pack }}
      run: dotnet pack -p:Version=${{ inputs.version }} -p:RepositoryCommit=${{ inputs.commit }}
      shell: pwsh
    - if: ${{ inputs.nuget-push-api-key }}
      run: dotnet nuget push ./artifacts/package/release/*.nupkg -k ${{ inputs.nuget-push-api-key }} -s https://api.nuget.org/v3/index.json
      shell: pwsh
    - if: ${{ !inputs.skip-store-artifact }}
      uses: actions/upload-artifact@v4
      with: 
        path: ./artifacts/package/release/*.*nupkg
        if-no-files-found: error
    - if: ${{ !inputs.skip-store-release }}
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/package/release/*.*nupkg
        
